name: Checks

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  copyright:
    runs-on: ubuntu-latest
    name: Copyrights

    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}